name: Brainset
favicon: null
layout_spectrum: 0.21363696735352278
typography_spectrum: 0.6887782095000148
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee202a'
    - '#ce9162'
    - '#0054a7'
    - '#3eab50'
  brandStrength: 0.6875
  lightness: 0.7042263441253453
  saturation: 0.5
  rhythmicContrast: 0.7835327091161162
purpose: []
